vim.cmd('autocmd FileType python colorscheme tokyonight')
vim.cmd('autocmd FileType java colorscheme gruvbox')
vim.cmd('autocmd FileType cpp colorscheme onedark')
vim.cmd('autocmd FileType css,html,javascript,typescript colorscheme onedark')
vim.cmd([[colorscheme tokyonight]])
